apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-deployment
  labels:
    app: lab2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab2
  template:
    metadata:
      labels:
        app: lab2
    spec:
      containers:
      - name: lab2
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: some-value
        - name: REACT_APP_COMPANY_NAME
          value: another-value

---

apiVersion: v1
kind: Service
metadata:
  name: lab2-service
spec:
  type: NodePort
  selector:
    app: lab2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100