apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lab3-app
  labels:
    app: lab3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab3
  template:
    metadata:
      labels:
        app: lab3
    spec:
      containers:
      - name: lab3-app
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
          - containerPort: 3000
        env:
          - name: REACT_APP_USERNAME
            valueFrom:
               configMapKeyRef:
                name: config-map
                key: REACT_APP_USERNAME
          - name: REACT_APP_COMPANY_NAME
            valueFrom:
               configMapKeyRef:
                name: config-map
                key: REACT_APP_COMPANY_NAME
